baseurl: "https://fushaolei.github.io/LifeLog"
languageCode: "en-us"
title: "琼西往事"
theme: "dark"
googleAnalytics: ""
DisqusShortname: "sorryfu"
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: 首页
      url: ""
      weight: 1
    - name: 关于
      url: "about/"
      weight: 2

# params:
#   description: "A website built through Hugo and blogdown."
#   footer: "&copy; [FuShaoLei](https://yihui.org) 2017 -- {Year} | [Github](https://github.com/yihui) | [Twitter](https://twitter.com/xieyihui)"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
